version: "3"
services:
  worker:
    image: ghcr.io/onmcu/dockerized-gha-runner:latest
    environment:
      RUNNER_SCOPE: org
      RUNNER_ORG: {{ GITHUB_RUNNER_ORG }}
      RUNNER_NAME: {{ GITHUB_RUNNER_NAME }}
      RUNNER_TOKEN: {{ GITHUB_RUNNER_TOKEN }}
      RUNNER_WORKDIR: /tmp/runner/work
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: /runner/data
      LABELS: linux,x64,gpu,rust
      DISABLE_AUTOMATIC_DEREGISTRATION: true
    volumes:
      - "./data:/runner/data:Z"
      - "./tmp:/tmp/runner:Z"
    security_opt:
      - label=disable
